import { Container } from 'inversify';
import { SessionCommand as SessionAJAXCommand } from '../Command/AJAX/SessionCommand';
import { StatsCommand as StatsAJAXCommand } from '../Command/AJAX/StatsCommand';
import { LocaleCommand as LocaleHeapCommand } from '../Command/Heap/LocaleCommand';
import { LanguageCommand as LanguageRedisCommand } from '../Command/Redis/LanguageCommand';
import { RegionCommand as RegionRedisCommand } from '../Command/Redis/RegionCommand';
import { AuthenticationMiddleware } from '../Controller/middlewares/AuthenticationMiddleware';
import { EntranceSaga } from '../Frontend/sagas/EntranceSaga';
import { IdentitySaga } from '../Frontend/sagas/IdentitySaga';
import { LogoutSaga } from '../Frontend/sagas/LogoutSaga';
import { RedirectSaga } from '../Frontend/sagas/RedirectSaga';
import { RootSaga } from '../Frontend/sagas/RootSaga';
import { StatsEditSaga } from '../Frontend/sagas/StatsEditSaga';
import { StatsListSaga } from '../Frontend/sagas/StatsListSaga';
import { AJAX } from '../General/AJAX/AJAX';
import { Heap } from '../General/Heap/Heap';
import { MySQL } from '../General/MySQL/MySQL';
import { Redis } from '../General/Redis/Redis';
import { veauMySQL } from '../Infrastructure/VeauMySQL';
import { veauRedis } from '../Infrastructure/VeauRedis';
import { veauVault } from '../Infrastructure/VeauVault';
import { AuthenticationInteractor } from '../Interactor/AuthenticationInteractor';
import { LocaleInteractor } from '../Interactor/LocaleInteractor';
import { StatsInteractor } from '../Interactor/StatsInteractor';
import { LocaleQuery as LocaleAJAXQuery } from '../Query/AJAX/LocaleQuery';
import { SessionQuery as SessionAJAXQuery } from '../Query/AJAX/SessionQuery';
import { StatsOutlineQuery as StatsOutlineAJAXQuery } from '../Query/AJAX/StatsOutlineQuery';
import { StatsQuery as StatsAJAXQuery } from '../Query/AJAX/StatsQuery';
import { LocaleQuery as LocaleHeapQuery } from '../Query/Heap/LocaleQuery';
import { LanguageQuery as LanguageKernelQuery } from '../Query/Kernel/LanguageQuery';
import { RegionQuery as RegionKernelQuery } from '../Query/Kernel/RegionQuery';
import { AccountQuery as AccountMySQLQuery } from '../Query/MySQL/AccountQuery';
import { LanguageQuery as LanguageMySQLQuery } from '../Query/MySQL/LanguageQuery';
import { RegionQuery as RegionMySQLQuery } from '../Query/MySQL/RegionQuery';
import { StatsItemQuery as StatsItemMySQLQuery } from '../Query/MySQL/StatsItemQuery';
import { StatsOutlineQuery as StatsOutlineMySQLQuery } from '../Query/MySQL/StatsOutlineQuery';
import { StatsQuery as StatsMySQLQuery } from '../Query/MySQL/StatsQuery';
import { StatsValueQuery as StatsValueMySQLQuery } from '../Query/MySQL/StatsValueQuery';
import { LanguageQuery as LanguageRedisQuery } from '../Query/Redis/LanguageQuery';
import { RegionQuery as RegionRedisQuery } from '../Query/Redis/RegionQuery';
import { LanguageQuery as LanguageVaultQuery } from '../Query/Vault/LanguageQuery';
import { LocaleQuery as LocaleVaultQuery } from '../Query/Vault/LocaleQuery';
import { RegionQuery as RegionVaultQuery } from '../Query/Vault/RegionQuery';
import { TYPE } from './Types';

export const kernel: Container = new Container();
export const vault: Container = new Container();

kernel.bind<LanguageRedisCommand>(TYPE.LanguageRedisCommand).to(LanguageRedisCommand).inSingletonScope();
kernel.bind<RegionRedisCommand>(TYPE.RegionRedisCommand).to(RegionRedisCommand).inSingletonScope();
kernel.bind<AuthenticationMiddleware>(TYPE.AuthenticationMiddleware).to(AuthenticationMiddleware).inSingletonScope();
kernel.bind<MySQL>(TYPE.MySQL).toConstantValue(veauMySQL);
kernel.bind<Redis>(TYPE.Redis).toConstantValue(veauRedis);
kernel.bind<AuthenticationInteractor>(TYPE.AuthenticationInteractor).to(AuthenticationInteractor).inSingletonScope();
kernel.bind<LocaleInteractor>(TYPE.LocaleInteractor).to(LocaleInteractor).inSingletonScope();
kernel.bind<StatsInteractor>(TYPE.StatsInteractor).to(StatsInteractor).inSingletonScope();
kernel.bind<LanguageKernelQuery>(TYPE.LanguageKernelQuery).to(LanguageKernelQuery).inSingletonScope();
kernel.bind<RegionKernelQuery>(TYPE.RegionKernelQuery).to(RegionKernelQuery).inSingletonScope();
kernel.bind<AccountMySQLQuery>(TYPE.AccountMySQLQuery).to(AccountMySQLQuery).inSingletonScope();
kernel.bind<LanguageMySQLQuery>(TYPE.LanguageMySQLQuery).to(LanguageMySQLQuery).inSingletonScope();
kernel.bind<RegionMySQLQuery>(TYPE.RegionMySQLQuery).to(RegionMySQLQuery).inSingletonScope();
kernel.bind<StatsItemMySQLQuery>(TYPE.StatsItemMySQLQuery).to(StatsItemMySQLQuery).inSingletonScope();
kernel.bind<StatsOutlineMySQLQuery>(TYPE.StatsOutlineMySQLQuery).to(StatsOutlineMySQLQuery).inSingletonScope();
kernel.bind<StatsMySQLQuery>(TYPE.StatsMySQLQuery).to(StatsMySQLQuery).inSingletonScope();
kernel.bind<StatsValueMySQLQuery>(TYPE.StatsValueMySQLQuery).to(StatsValueMySQLQuery).inSingletonScope();
kernel.bind<LanguageRedisQuery>(TYPE.LanguageRedisQuery).to(LanguageRedisQuery).inSingletonScope();
kernel.bind<RegionRedisQuery>(TYPE.RegionRedisQuery).to(RegionRedisQuery).inSingletonScope();

vault.bind<AJAX>(TYPE.AJAX).toConstantValue(new AJAX());
vault.bind<Heap>(TYPE.Vault).toConstantValue(veauVault);
vault.bind<SessionAJAXCommand>(TYPE.SessionAJAXCommand).to(SessionAJAXCommand).inSingletonScope();
vault.bind<StatsAJAXCommand>(TYPE.StatsAJAXCommand).to(StatsAJAXCommand).inSingletonScope();
vault.bind<LocaleHeapCommand>(TYPE.LocaleHeapCommand).to(LocaleHeapCommand).inSingletonScope();
vault.bind<EntranceSaga>(TYPE.EntranceSaga).to(EntranceSaga).inSingletonScope();
vault.bind<IdentitySaga>(TYPE.IdentitySaga).to(IdentitySaga).inSingletonScope();
vault.bind<LogoutSaga>(TYPE.LogoutSaga).to(LogoutSaga).inSingletonScope();
vault.bind<RedirectSaga>(TYPE.RedirectSaga).to(RedirectSaga).inSingletonScope();
vault.bind<RootSaga>(TYPE.RootSaga).to(RootSaga).inSingletonScope();
vault.bind<StatsEditSaga>(TYPE.StatsEditSaga).to(StatsEditSaga).inSingletonScope();
vault.bind<StatsListSaga>(TYPE.StatsListSaga).to(StatsListSaga).inSingletonScope();
vault.bind<LocaleAJAXQuery>(TYPE.LocaleAJAXQuery).to(LocaleAJAXQuery).inSingletonScope();
vault.bind<SessionAJAXQuery>(TYPE.SessionAJAXQuery).to(SessionAJAXQuery).inSingletonScope();
vault.bind<StatsOutlineAJAXQuery>(TYPE.StatsOutlineAJAXQuery).to(StatsOutlineAJAXQuery).inSingletonScope();
vault.bind<StatsAJAXQuery>(TYPE.StatsAJAXQuery).to(StatsAJAXQuery).inSingletonScope();
vault.bind<LocaleHeapQuery>(TYPE.LocaleHeapQuery).to(LocaleHeapQuery).inSingletonScope();
vault.bind<LanguageVaultQuery>(TYPE.LanguageVaultQuery).to(LanguageVaultQuery).inSingletonScope();
vault.bind<LocaleVaultQuery>(TYPE.LocaleVaultQuery).to(LocaleVaultQuery).inSingletonScope();
vault.bind<RegionVaultQuery>(TYPE.RegionVaultQuery).to(RegionVaultQuery).inSingletonScope();
