type DIType = Readonly<{
  SessionAJAXCommand: symbol;
  StatsAJAXCommand: symbol;
  LocaleCacheCommand: symbol;
  StatsKernelCommand: symbol;
  LanguageRedisCommand: symbol;
  RegionRedisCommand: symbol;
  AuthenticationMiddleware: symbol;
  EntranceEpic: symbol;
  IdentityEpic: symbol;
  LogoutEpic: symbol;
  RedirectEpic: symbol;
  RootEpic: symbol;
  StatsEditEpic: symbol;
  StatsListEpic: symbol;
  AJAX: symbol;
  Cache: symbol;
  MySQL: symbol;
  Redis: symbol;
  AuthenticationInteractor: symbol;
  LocaleInteractor: symbol;
  StatsInteractor: symbol;
  LocaleAJAXQuery: symbol;
  StatsOutlineAJAXQuery: symbol;
  StatsAJAXQuery: symbol;
  VeauAccountAJAXQuery: symbol;
  LocaleCacheQuery: symbol;
  TermCacheQuery: symbol;
  LanguageKernelQuery: symbol;
  RegionKernelQuery: symbol;
  StatsKernelQuery: symbol;
  AccountMySQLQuery: symbol;
  LanguageMySQLQuery: symbol;
  RegionMySQLQuery: symbol;
  StatsItemMySQLQuery: symbol;
  StatsOutlineMySQLQuery: symbol;
  StatsValueMySQLQuery: symbol;
  LanguageRedisQuery: symbol;
  RegionRedisQuery: symbol;
  IdentityVaultQuery: symbol;
  LanguageVaultQuery: symbol;
  LocaleVaultQuery: symbol;
  RegionVaultQuery: symbol;
  StatsListItemVaultQuery: symbol;
}>;

export const Type: DIType = {
  SessionAJAXCommand: Symbol(),
  StatsAJAXCommand: Symbol(),
  LocaleCacheCommand: Symbol(),
  StatsKernelCommand: Symbol(),
  LanguageRedisCommand: Symbol(),
  RegionRedisCommand: Symbol(),
  AuthenticationMiddleware: Symbol(),
  EntranceEpic: Symbol(),
  IdentityEpic: Symbol(),
  LogoutEpic: Symbol(),
  RedirectEpic: Symbol(),
  RootEpic: Symbol(),
  StatsEditEpic: Symbol(),
  StatsListEpic: Symbol(),
  AJAX: Symbol(),
  Cache: Symbol(),
  MySQL: Symbol(),
  Redis: Symbol(),
  AuthenticationInteractor: Symbol(),
  LocaleInteractor: Symbol(),
  StatsInteractor: Symbol(),
  LocaleAJAXQuery: Symbol(),
  StatsOutlineAJAXQuery: Symbol(),
  StatsAJAXQuery: Symbol(),
  VeauAccountAJAXQuery: Symbol(),
  LocaleCacheQuery: Symbol(),
  TermCacheQuery: Symbol(),
  LanguageKernelQuery: Symbol(),
  RegionKernelQuery: Symbol(),
  StatsKernelQuery: Symbol(),
  AccountMySQLQuery: Symbol(),
  LanguageMySQLQuery: Symbol(),
  RegionMySQLQuery: Symbol(),
  StatsItemMySQLQuery: Symbol(),
  StatsOutlineMySQLQuery: Symbol(),
  StatsValueMySQLQuery: Symbol(),
  LanguageRedisQuery: Symbol(),
  RegionRedisQuery: Symbol(),
  IdentityVaultQuery: Symbol(),
  LanguageVaultQuery: Symbol(),
  LocaleVaultQuery: Symbol(),
  RegionVaultQuery: Symbol(),
  StatsListItemVaultQuery: Symbol()
};
