/* eslint-disable  @typescript-eslint/typedef */

export const Type = {
  SessionAJAXCommand: Symbol(),
  StatsAJAXCommand: Symbol(),
  LocaleCacheCommand: Symbol(),
  StatsKernelCommand: Symbol(),
  LanguageRedisCommand: Symbol(),
  RegionRedisCommand: Symbol(),
  EntranceEpic: Symbol(),
  IdentityEpic: Symbol(),
  LogoutEpic: Symbol(),
  RedirectEpic: Symbol(),
  RootEpic: Symbol(),
  StatsEditEpic: Symbol(),
  StatsListEpic: Symbol(),
  AJAX: Symbol(),
  Cache: Symbol(),
  MySQL: Symbol(),
  Redis: Symbol(),
  AuthenticationInteractor: Symbol(),
  LocaleInteractor: Symbol(),
  StatsInteractor: Symbol(),
  LocaleAJAXQuery: Symbol(),
  StatsOutlineAJAXQuery: Symbol(),
  StatsAJAXQuery: Symbol(),
  VeauAccountAJAXQuery: Symbol(),
  LocaleCacheQuery: Symbol(),
  TermCacheQuery: Symbol(),
  LanguageKernelQuery: Symbol(),
  RegionKernelQuery: Symbol(),
  StatsKernelQuery: Symbol(),
  AccountMySQLQuery: Symbol(),
  LanguageMySQLQuery: Symbol(),
  RegionMySQLQuery: Symbol(),
  StatsItemMySQLQuery: Symbol(),
  StatsOutlineMySQLQuery: Symbol(),
  StatsValueMySQLQuery: Symbol(),
  LanguageRedisQuery: Symbol(),
  RegionRedisQuery: Symbol(),
  IdentityVaultQuery: Symbol(),
  LanguageVaultQuery: Symbol(),
  LocaleVaultQuery: Symbol(),
  RegionVaultQuery: Symbol(),
  StatsListItemVaultQuery: Symbol()
} as const;
