type DIType = Readonly<{
  SessionAJAXCommand: symbol;
  StatsAJAXCommand: symbol;
  LocaleCacheCommand: symbol;
  StatsKernelCommand: symbol;
  LanguageRedisCommand: symbol;
  RegionRedisCommand: symbol;
  AuthenticationMiddleware: symbol;
  EntranceEpic: symbol;
  IdentityEpic: symbol;
  LogoutEpic: symbol;
  RedirectEpic: symbol;
  RootEpic: symbol;
  StatsEditEpic: symbol;
  StatsListEpic: symbol;
  AJAX: symbol;
  Cache: symbol;
  MySQL: symbol;
  Redis: symbol;
  AuthenticationInteractor: symbol;
  LocaleInteractor: symbol;
  StatsInteractor: symbol;
  LocaleAJAXQuery: symbol;
  StatsOutlineAJAXQuery: symbol;
  StatsAJAXQuery: symbol;
  VeauAccountAJAXQuery: symbol;
  LocaleCacheQuery: symbol;
  LanguageKernelQuery: symbol;
  RegionKernelQuery: symbol;
  StatsKernelQuery: symbol;
  AccountMySQLQuery: symbol;
  LanguageMySQLQuery: symbol;
  RegionMySQLQuery: symbol;
  StatsItemMySQLQuery: symbol;
  StatsOutlineMySQLQuery: symbol;
  StatsValueMySQLQuery: symbol;
  LanguageRedisQuery: symbol;
  RegionRedisQuery: symbol;
  IdentityVaultQuery: symbol;
  LanguageVaultQuery: symbol;
  LocaleVaultQuery: symbol;
  RegionVaultQuery: symbol;
}>;

export const TYPE: DIType = {
  SessionAJAXCommand: Symbol('SessionAJAXCommand'),
  StatsAJAXCommand: Symbol('StatsAJAXCommand'),
  LocaleCacheCommand: Symbol('LocaleCacheCommand'),
  StatsKernelCommand: Symbol('StatsKernelCommand'),
  LanguageRedisCommand: Symbol('LanguageRedisCommand'),
  RegionRedisCommand: Symbol('RegionRedisCommand'),
  AuthenticationMiddleware: Symbol('AuthenticationMiddleware'),
  EntranceEpic: Symbol('EntranceEpic'),
  IdentityEpic: Symbol('IdentityEpic'),
  LogoutEpic: Symbol('LogoutEpic'),
  RedirectEpic: Symbol('RedirectEpic'),
  RootEpic: Symbol('RootEpic'),
  StatsEditEpic: Symbol('StatsEditEpic'),
  StatsListEpic: Symbol('StatsListEpic'),
  AJAX: Symbol('AJAX'),
  Cache: Symbol('Cache'),
  MySQL: Symbol('MySQL'),
  Redis: Symbol('Redis'),
  AuthenticationInteractor: Symbol('AuthenticationInteractor'),
  LocaleInteractor: Symbol('LocaleInteractor'),
  StatsInteractor: Symbol('StatsInteractor'),
  LocaleAJAXQuery: Symbol('LocaleAJAXQuery'),
  StatsOutlineAJAXQuery: Symbol('StatsOutlineAJAXQuery'),
  StatsAJAXQuery: Symbol('StatsAJAXQuery'),
  VeauAccountAJAXQuery: Symbol('VeauAccountAJAXQuery'),
  LocaleCacheQuery: Symbol('LocaleCacheQuery'),
  LanguageKernelQuery: Symbol('LanguageKernelQuery'),
  RegionKernelQuery: Symbol('RegionKernelQuery'),
  StatsKernelQuery: Symbol('StatsKernelQuery'),
  AccountMySQLQuery: Symbol('AccountMySQLQuery'),
  LanguageMySQLQuery: Symbol('LanguageMySQLQuery'),
  RegionMySQLQuery: Symbol('RegionMySQLQuery'),
  StatsItemMySQLQuery: Symbol('StatsItemMySQLQuery'),
  StatsOutlineMySQLQuery: Symbol('StatsOutlineMySQLQuery'),
  StatsValueMySQLQuery: Symbol('StatsValueMySQLQuery'),
  LanguageRedisQuery: Symbol('LanguageRedisQuery'),
  RegionRedisQuery: Symbol('RegionRedisQuery'),
  IdentityVaultQuery: Symbol('IdentityVaultQuery'),
  LanguageVaultQuery: Symbol('LanguageVaultQuery'),
  LocaleVaultQuery: Symbol('LocaleVaultQuery'),
  RegionVaultQuery: Symbol('RegionVaultQuery')
};
