version: '3'
services:
  veau_mysql:
    container_name: 'veau_mysql'
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'veau'
      MYSQL_DATABASE: 'veau'
    volumes:
      - '$PWD/mysql/cnf:/etc/mysql/conf.d'
      - '$PWD/mysql/initdata:/docker-entrypoint-initdb.d'
  veau_redis:
    container_name: 'veau_redis'
    image: 'redis:5.0.4-alpine'
  veau_nginx:
    container_name: 'veau_nginx'
    image: 'nginx:1.15.11-alpine'
    ports:
      - '443:443'
    volumes:
      - '$PWD/nginx/veau.conf:/etc/nginx/conf.d/veau.conf'
      - '$PWD/cert/ssl.jamashita.dev.crt:/etc/nginx/conf.d/server.crt'
      - '$PWD/cert/ssl.jamashita.dev.key:/etc/nginx/conf.d/server.key'
    links:
      - 'veau'
  veau:
    container_name: 'veau'
    image: 'gcr.io/veau-229916/veau:latest'
    environment:
      NODE_ENV: 'demo'
    ports:
      - '4000:4000'
    links:
      - 'veau_mysql'
      - 'veau_redis'
