version: '3'
services:
  veau_mysql:
    container_name: 'veau_mysql'
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'veau'
      MYSQL_DATABASE: 'veau'
    volumes:
      - '$PWD/mysql/cnf:/etc/mysql/conf.d'
      - '$PWD/mysql/initdata:/docker-entrypoint-initdb.d'
  veau_redis:
    container_name: 'veau_redis'
    image: 'redis:4.0.11-alpine'
  veau_nginx:
    container_name: 'veau_nginx'
    image: 'nginx:1.15.8-alpine'
    ports:
      - '80:80'
    volumes:
      - '$PWD/nginx:/etc/nginx/conf.d'
    links:
      - 'veau'
  veau:
    container_name: 'veau'
    image: 'gcr.io/veau-229916/veau:latest'
    environment:
      NODE_ENV: 'staging'
    ports:
      - '4000:4000'
    links:
      - 'veau_mysql'
      - 'veau_redis'
