port: 4000
session:
  secret: 'iASDFnPvDbvG8xZS6njmtpBXZz7BP2jQ'
  maxAge: 28800000
redis:
  host: 'localhost'
  port: 6379
mysql:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
