port: 3000
session:
  secret: 'Ziuye5J4VmwxacL7dvV98dqUqT7HbfTn'
  maxAge: 28800000
  secure: false
redis:
  host: 'localhost'
  port: 6380
mysql:
  host: 'localhost'
  port: 3310
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
