port: 3000
cookieParser: 'TE1tZls3AWpetraaWtr1LpQUBbq8gLGs'
session:
  secret: 'Ziuye5J4VmwxacL7dvV98dqUqT7HbfTn'
  maxAge: 28800000
redis:
  host: '127.0.0.1'
  port: 6380
mysql:
  host: '127.0.0.1'
  port: 3310
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
