port: 3000
cookieParser: 'efYcPnffDE7C1ykkzzZRaAuD7eNo43EA'
session:
  secret: 'EXj92PpnRaa1UaKiCQdc3GhkZ8TQqaPK'
redis:
  host: 'veau_redis'
  port: 6379
mysql:
  host: 'veau_mysql'
  port: 3306
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
