port: 3000
redis:
  host: '127.0.0.1'
  port: 6380
mysql:
  host: '127.0.0.1'
  port: 3310
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
