port: 4000
redis:
  host: 'localhost'
  port: 6379
mysql:
  host: '172.30.192.4'
  port: 3306
  user: 'root'
  password: 'icPtQWE9op46nx2z7GEMqzbUm0EpxBT8'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000