port: 4000
redis:
  host: 'veau_redis'
  port: 6379
mysql:
  host: 'veau_mysql'
  port: 3306
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
log4js:
  appenders:
    file:
      type: 'dateFile'
      filename: 'logs/veau.log'
      pattern: '-yyyy-MM-dd.log'
      daysToKeep: 30
      layout:
        type: 'coloured'
    console:
      type: 'console'
      layout:
        type: 'coloured'
  categories:
    default:
      appenders:
        - 'file'
        - 'console'
      level: 'info'
  pm2: true
