port: 4000
redis:
  host: 'veau_redis'
  port: 6379
mysql:
  host: 'veau_mysql'
  port: 3306
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000