port: 4000
session:
  cookieName: 'VEAU'
  secret: 'lrs8lc9hkop1dxv9efxwujcdsk10iyx8zb5pkn0wv524c83s9xpv6x9koskp00qu'
  salt: '6RX59PsS0KQUfYWl'
redis:
  host: 'veau_redis'
  port: 6379
mysql:
  host: 'veau_mysql'
  port: 3306
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  dateStrings: true
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
