port: 3000
cookieParser: 'dIU8iSxRLHxppDAOJ1UcJOhPcgDAJss8'
session:
  secret: '5xPNqhCgHafvkDQzlcY51iCfUPJvVTnD'
  maxAge: 3600000
redis:
  host: 'veau_redis'
  port: 6379
mysql:
  host: 'veau_mysql'
  port: 3306
  user: 'root'
  password: 'veau'
  database: 'veau'
  charset: 'utf8mb4'
  connectionLimit: 50
  connectTimeout: 60000
  acquireTimeout: 60000
