apiVersion: 'extensions/v1beta1'
kind: 'Ingress'
metadata:
  name: 'veau-ingress'
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.global-static-ip-name: 'veau-ip'
spec:
  tls:
    - secretName: 'veau-cert'
  rules:
    - http:
        paths:
          - path: '/*'
            backend:
              serviceName: 'veau-service'
              servicePort: 9000
