version: '3'
services:
  veau_mysql:
    container_name: 'veau_mysql'
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'veau'
      MYSQL_DATABASE: 'veau'
    volumes:
    - './mysql/cnf:/etc/mysql/conf.d'
    - './mysql/initdata:/docker-entrypoint-initdb.d'
    ports:
    - '3310:3306'
  veau_redis:
    container_name: 'veau_redis'
    image: 'redis:4.0.11-alpine'
    ports:
    - '6380:6379'
