import { Container } from 'inversify';
import { SessionCommand as SessionAJAXCommand } from '../veau-command/AJAX/SessionCommand';
import { StatsCommand as StatsAJAXCommand } from '../veau-command/AJAX/StatsCommand';
import { LanguageCommand as LanguageRedisCommand } from '../veau-command/Redis/LanguageCommand';
import { RegionCommand as RegionRedisCommand } from '../veau-command/Redis/RegionCommand';
import { AuthenticationMiddleware } from '../veau-controller/middlewares/AuthenticationMiddleware';
import { AJAX } from '../veau-general/AJAX/AJAX';
import { MySQL } from '../veau-general/MySQL/MySQL';
import { Redis } from '../veau-general/Redis/Redis';
import { veauMySQL } from '../veau-infrastructure/VeauMySQL';
import { veauRedis } from '../veau-infrastructure/VeauRedis';
import { AuthenticationInteractor } from '../veau-interactor/AuthenticationInteractor';
import { LocaleInteractor } from '../veau-interactor/LocaleInteractor';
import { StatsInteractor } from '../veau-interactor/StatsInteractor';
import { AccountQuery } from '../veau-query/AccountQuery';
import { LocaleQuery as LocaleAJAXQuery } from '../veau-query/AJAX/LocaleQuery';
import { SessionQuery as SessionAJAXQuery } from '../veau-query/AJAX/SessionQuery';
import { LanguageQuery } from '../veau-query/LanguageQuery';
import { AccountQuery as AccountMySQLQuery } from '../veau-query/MySQL/AccountQuery';
import { LanguageQuery as LanguageMySQLQuery } from '../veau-query/MySQL/LanguageQuery';
import { RegionQuery as RegionMySQLQuery } from '../veau-query/MySQL/RegionQuery';
import { StatsItemQuery as StatsItemMySQLQuery } from '../veau-query/MySQL/StatsItemQuery';
import { StatsOutlineQuery as StatsOutlineMySQLQuery } from '../veau-query/MySQL/StatsOutlineQuery';
import { StatsQuery as StatsMySQLQuery } from '../veau-query/MySQL/StatsQuery';
import { StatsValueQuery as StatsValueMySQLQuery } from '../veau-query/MySQL/StatsValueQuery';
import { LanguageQuery as LanguageRedisQuery } from '../veau-query/Redis/LanguageQuery';
import { RegionQuery as RegionRedisQuery } from '../veau-query/Redis/RegionQuery';
import { RegionQuery } from '../veau-query/RegionQuery';
import { StatsItemQuery } from '../veau-query/StatsItemQuery';
import { StatsOutlineQuery } from '../veau-query/StatsOutlineQuery';
import { StatsQuery } from '../veau-query/StatsQuery';
import { StatsValueQuery } from '../veau-query/StatsValueQuery';
import { TYPE } from './Types';

export const kernel: Container = new Container();
export const vault: Container = new Container();

kernel.bind<LanguageRedisCommand>(TYPE.LanguageRedisCommand).to(LanguageRedisCommand).inSingletonScope();
kernel.bind<RegionRedisCommand>(TYPE.RegionRedisCommand).to(RegionRedisCommand).inSingletonScope();
kernel.bind<AuthenticationMiddleware>(TYPE.AuthenticationMiddleware).to(AuthenticationMiddleware).inSingletonScope();
kernel.bind<MySQL>(TYPE.MySQL).toConstantValue(veauMySQL);
kernel.bind<Redis>(TYPE.Redis).toConstantValue(veauRedis);
kernel.bind<AuthenticationInteractor>(TYPE.AuthenticationInteractor).to(AuthenticationInteractor).inSingletonScope();
kernel.bind<LocaleInteractor>(TYPE.LocaleInteractor).to(LocaleInteractor).inSingletonScope();
kernel.bind<StatsInteractor>(TYPE.StatsInteractor).to(StatsInteractor).inSingletonScope();
kernel.bind<AccountQuery>(TYPE.AccountQuery).to(AccountQuery).inSingletonScope();
kernel.bind<LanguageQuery>(TYPE.LanguageQuery).to(LanguageQuery).inSingletonScope();
kernel.bind<RegionQuery>(TYPE.RegionQuery).to(RegionQuery).inSingletonScope();
kernel.bind<StatsItemQuery>(TYPE.StatsItemQuery).to(StatsItemQuery).inSingletonScope();
kernel.bind<StatsOutlineQuery>(TYPE.StatsOutlineQuery).to(StatsOutlineQuery).inSingletonScope();
kernel.bind<StatsQuery>(TYPE.StatsQuery).to(StatsQuery).inSingletonScope();
kernel.bind<StatsValueQuery>(TYPE.StatsValueQuery).to(StatsValueQuery).inSingletonScope();
kernel.bind<AccountMySQLQuery>(TYPE.AccountMySQLQuery).to(AccountMySQLQuery).inSingletonScope();
kernel.bind<LanguageMySQLQuery>(TYPE.LanguageMySQLQuery).to(LanguageMySQLQuery).inSingletonScope();
kernel.bind<RegionMySQLQuery>(TYPE.RegionMySQLQuery).to(RegionMySQLQuery).inSingletonScope();
kernel.bind<StatsItemMySQLQuery>(TYPE.StatsItemMySQLQuery).to(StatsItemMySQLQuery).inSingletonScope();
kernel.bind<StatsOutlineMySQLQuery>(TYPE.StatsOutlineMySQLQuery).to(StatsOutlineMySQLQuery).inSingletonScope();
kernel.bind<StatsMySQLQuery>(TYPE.StatsMySQLQuery).to(StatsMySQLQuery).inSingletonScope();
kernel.bind<StatsValueMySQLQuery>(TYPE.StatsValueMySQLQuery).to(StatsValueMySQLQuery).inSingletonScope();
kernel.bind<LanguageRedisQuery>(TYPE.LanguageRedisQuery).to(LanguageRedisQuery).inSingletonScope();
kernel.bind<RegionRedisQuery>(TYPE.RegionRedisQuery).to(RegionRedisQuery).inSingletonScope();

vault.bind<AJAX>(TYPE.AJAX).toConstantValue(new AJAX());
vault.bind<SessionAJAXCommand>(TYPE.SessionAJAXCommand).to(SessionAJAXCommand).inSingletonScope();
vault.bind<StatsAJAXCommand>(TYPE.StatsAJAXCommand).to(StatsAJAXCommand).inSingletonScope();
vault.bind<LocaleAJAXQuery>(TYPE.LocaleAJAXQuery).to(LocaleAJAXQuery).inSingletonScope();
vault.bind<SessionAJAXQuery>(TYPE.SessionAJAXQuery).to(SessionAJAXQuery).inSingletonScope();
