export type DIType = {
  SessionAJAXCommand: symbol;
  StatsAJAXCommand: symbol;
  LocaleHeapCommand: symbol;
  LanguageRedisCommand: symbol;
  RegionRedisCommand: symbol;
  AuthenticationMiddleware: symbol;
  AJAX: symbol;
  Vault: symbol;
  MySQL: symbol;
  Redis: symbol;
  AuthenticationInteractor: symbol;
  LocaleInteractor: symbol;
  StatsInteractor: symbol;
  AccountQuery: symbol;
  LanguageQuery: symbol;
  RegionQuery: symbol;
  StatsItemQuery: symbol;
  StatsOutlineQuery: symbol;
  StatsQuery: symbol;
  StatsValueQuery: symbol;
  LocaleAJAXQuery: symbol;
  SessionAJAXQuery: symbol;
  LocaleHeapQuery: symbol;
  AccountMySQLQuery: symbol;
  LanguageMySQLQuery: symbol;
  RegionMySQLQuery: symbol;
  StatsItemMySQLQuery: symbol;
  StatsOutlineMySQLQuery: symbol;
  StatsMySQLQuery: symbol;
  StatsValueMySQLQuery: symbol;
  LanguageRedisQuery: symbol;
  RegionRedisQuery: symbol;
};

export const TYPE: DIType = {
  SessionAJAXCommand: Symbol('SessionAJAXCommand'),
  StatsAJAXCommand: Symbol('StatsAJAXCommand'),
  LocaleHeapCommand: Symbol('LocaleHeapCommand'),
  LanguageRedisCommand: Symbol('LanguageRedisCommand'),
  RegionRedisCommand: Symbol('RegionRedisCommand'),
  AuthenticationMiddleware: Symbol('AuthenticationMiddleware'),
  AJAX: Symbol('AJAX'),
  Vault: Symbol('Vault'),
  MySQL: Symbol('MySQL'),
  Redis: Symbol('Redis'),
  AuthenticationInteractor: Symbol('AuthenticationInteractor'),
  LocaleInteractor: Symbol('LocaleInteractor'),
  StatsInteractor: Symbol('StatsInteractor'),
  AccountQuery: Symbol('AccountQuery'),
  LanguageQuery: Symbol('LanguageQuery'),
  RegionQuery: Symbol('RegionQuery'),
  StatsItemQuery: Symbol('StatsItemQuery'),
  StatsOutlineQuery: Symbol('StatsOutlineQuery'),
  StatsQuery: Symbol('StatsQuery'),
  StatsValueQuery: Symbol('StatsValueQuery'),
  LocaleAJAXQuery: Symbol('LocaleAJAXQuery'),
  SessionAJAXQuery: Symbol('SessionAJAXQuery'),
  LocaleHeapQuery: Symbol('LocaleHeapQuery'),
  AccountMySQLQuery: Symbol('AccountMySQLQuery'),
  LanguageMySQLQuery: Symbol('LanguageMySQLQuery'),
  RegionMySQLQuery: Symbol('RegionMySQLQuery'),
  StatsItemMySQLQuery: Symbol('StatsItemMySQLQuery'),
  StatsOutlineMySQLQuery: Symbol('StatsOutlineMySQLQuery'),
  StatsMySQLQuery: Symbol('StatsMySQLQuery'),
  StatsValueMySQLQuery: Symbol('StatsValueMySQLQuery'),
  LanguageRedisQuery: Symbol('LanguageRedisQuery'),
  RegionRedisQuery: Symbol('RegionRedisQuery')
};
