name: 'Deployment to Google Kubernetes Engine'
on:
  push:
    branches:
      - 'release/*'
env:
  GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
jobs:
  gcp-deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    steps:
      - name: 'Use Node.js 14.5'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.5'
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'GCP Authenticate'
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@master'
        with:
          project_id: '$GCP_PROJECT_ID'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true
      - name: 'Deploy to Cloud Run'
        run: |
          AS_OF=`date +%Y%m%d%H%M%S`
          IMAGE=gcr.io/$GCP_PROJECT_ID/veau:${AS_OF}
          docker build . -t $IMAGE
          docker push $IMAGE
