name: 'Validate Codes'
on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
jobs:
  code-validation:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    steps:
      - name: 'Use node.js 14.5'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '14.5'
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
        with:
          ref: '${{github.head_ref}}'
      - name: 'validate TS files'
        run: |
          yarn install --frozen-lockfile
          yarn format
          yarn test
